export const ALL_GIFS = [
    { id: 'g1', url: 'https://media.giphy.com/media/Od57K1hlygXW8/giphy.gif' },
    { id: 'g2', url: 'https://media.giphy.com/media/ICOgUNjpvO0PC/giphy.gif' },
    { id: 'g3', url: 'https://media.giphy.com/media/l0HlBO7eyXzSZkJri/giphy.gif' },
    { id: 'g4', url: 'https://media.giphy.com/media/3oEjI6SIIHBdRxXI40/giphy.gif' },
    { id: 'g5', url: 'https://media.giphy.com/media/xT9IgG50Fb7Mi0prBC/giphy.gif' },
    { id: 'g6', url: 'https://media.giphy.com/media/5GoVLqeAOo6PK/giphy.gif' },
    { id: 'g7', url: 'https://media.giphy.com/media/26ufdipQqU2lhNA4g/giphy.gif' },
    { id: 'g8', url: 'https://media.giphy.com/media/l4FGpP4lxGGgK5CBW/giphy.gif' },
    { id: 'g9', url: 'https://media.giphy.com/media/3oriO0OEd9QIDdllqo/giphy.gif' },
    { id: 'g10', url: 'https://media.giphy.com/media/13CoXDiaCcCoyk/giphy.gif' },

    { id: 'g11', url: 'https://media.giphy.com/media/11sBLVxNs7v6WA/giphy.gif' },
    { id: 'g12', url: 'https://media.giphy.com/media/26BRuo6sLetdllPAQ/giphy.gif' },
    { id: 'g13', url: 'https://media.giphy.com/media/l378khQxt68syiWJy/giphy.gif' },
    { id: 'g14', url: 'https://media.giphy.com/media/fAnEC88LccN7a/giphy.gif' },
    { id: 'g15', url: 'https://media.giphy.com/media/3o7TKTDn976rzVgky4/giphy.gif' },
    { id: 'g16', url: 'https://media.giphy.com/media/QBd2kLB5qDmysEXre9/giphy.gif' },
    { id: 'g17', url: 'https://media.giphy.com/media/l3q2K5jinAlChoCLS/giphy.gif' },
    { id: 'g18', url: 'https://media.giphy.com/media/26xBI73gWquCBBCDe/giphy.gif' },
    { id: 'g19', url: 'https://media.giphy.com/media/3o6Zt481isNVuQI1l6/giphy.gif' },
    { id: 'g20', url: 'https://media.giphy.com/media/12XDYvMJNcmLgQ/giphy.gif' },

    { id: 'g21', url: 'https://media.giphy.com/media/14uQ3cOFteDaU/giphy.gif' },
    { id: 'g22', url: 'https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif' },
    { id: 'g23', url: 'https://media.giphy.com/media/1BXa2alBjrCXC/giphy.gif' },
    { id: 'g24', url: 'https://media.giphy.com/media/10LKovKon8DENq/giphy.gif' },
    { id: 'g25', url: 'https://media.giphy.com/media/3NtY188QaxDdC/giphy.gif' },
    { id: 'g26', url: 'https://media.giphy.com/media/3o7abB06u9bNzA8lu8/giphy.gif' },
    { id: 'g27', url: 'https://media.giphy.com/media/xUPGcguWZHRC2HyBRS/giphy.gif' },
    { id: 'g28', url: 'https://media.giphy.com/media/26gsjCZpPolPr3sBy/giphy.gif' },
    { id: 'g29', url: 'https://media.giphy.com/media/l4EoTHjQf2v2Hj4vm/giphy.gif' },
    { id: 'g30', url: 'https://media.giphy.com/media/ASd0Ukj0y3qMM/giphy.gif' },
    // Еще 30 GIF (31-60)

    { id: 'g31', url: 'https://media.giphy.com/media/3oEjHAUOqG3lSS0f1C/giphy.gif' },
    { id: 'g32', url: 'https://media.giphy.com/media/xT0xeJpnrWC4XWblEk/giphy.gif' },
    { id: 'g33', url: 'https://media.giphy.com/media/l4FGuhL4U2WyjdkaY/giphy.gif' },
    { id: 'g34', url: 'https://media.giphy.com/media/26ufnwz3wDUli7GU0/giphy.gif' },
    { id: 'g35', url: 'https://media.giphy.com/media/3o7TKMt1VVNkHV2PaE/giphy.gif' },
    { id: 'g36', url: 'https://media.giphy.com/media/l0MYEqEzwMWFCg8rm/giphy.gif' },
    { id: 'g37', url: 'https://media.giphy.com/media/26BRv0ThflsHCqDrG/giphy.gif' },
    { id: 'g38', url: 'https://media.giphy.com/media/3o6Mb43lhxy1A1FHgA/giphy.gif' },
    { id: 'g39', url: 'https://media.giphy.com/media/xT9DPIBYf0pAviBLzO/giphy.gif' },
    { id: 'g40', url: 'https://media.giphy.com/media/26gs6vEzlpaxuYgso/giphy.gif' },

    { id: 'g41', url: 'https://media.giphy.com/media/3o7TKsQ8UQ4lT4G8BW/giphy.gif' },
    { id: 'g42', url: 'https://media.giphy.com/media/l0HlNQ03J5JxX6lva/giphy.gif' },
    { id: 'g43', url: 'https://media.giphy.com/media/xT5LMHxhOfscxPfIfm/giphy.gif' },
    { id: 'g44', url: 'https://media.giphy.com/media/26BRBKqUiq586bRVm/giphy.gif' },
    { id: 'g45', url: 'https://media.giphy.com/media/3oEjI5VtIhHvK37WYo/giphy.gif' },
    { id: 'g46', url: 'https://media.giphy.com/media/l4FGq2fL0o3m4M5ig/giphy.gif' },
    { id: 'g47', url: 'https://media.giphy.com/media/26ufcYAkp8e66vanu/giphy.gif' },
    { id: 'g48', url: 'https://media.giphy.com/media/xT0BKpqAaJczduXXJ6/giphy.gif' },
    { id: 'g49', url: 'https://media.giphy.com/media/3o6ZtpxSZbQRRnwCKQ/giphy.gif' },
    { id: 'g50', url: 'https://media.giphy.com/media/l4FGGafcOHmrlQxG0/giphy.gif' },

    { id: 'g51', url: 'https://media.giphy.com/media/26AHONQ79FdWZhAI0/giphy.gif' },
    { id: 'g52', url: 'https://media.giphy.com/media/xT9IgzoKnwFNmISR8I/giphy.gif' },
    { id: 'g53', url: 'https://media.giphy.com/media/3o7aD2saalBwwftBIY/giphy.gif' },
    { id: 'g54', url: 'https://media.giphy.com/media/l0ExncehJzexFpRHq/giphy.gif' },
    { id: 'g55', url: 'https://media.giphy.com/media/26gs9oNcFxokURtvO/giphy.gif' },
    { id: 'g56', url: 'https://media.giphy.com/media/xT0xeuOy2Fcl9vDGiA/giphy.gif' },
    { id: 'g57', url: 'https://media.giphy.com/media/3o7TKP9ln2Dr6ze6f6/giphy.gif' },
    { id: 'g58', url: 'https://media.giphy.com/media/l4FGJb8H6B5f4Q8Ra/giphy.gif' },
    { id: 'g59', url: 'https://media.giphy.com/media/26uf4u3K7G0J9acFy/giphy.gif' },
    { id: 'g60', url: 'https://media.giphy.com/media/xT9DPlAUKTl1GeZjC8/giphy.gif' },
];