export const TEMP_UNLOCK_ALL_AVATAR_FRAMES = false;

// name/description/condition хранят i18n-ключи; перевод выполняется в компонентах через t().
export const avatarFrames = [
    {
        key: "none",
        name: "frameNone.name",
        description: "frameNone.desc",
        imagePath: null,
        condition: "frameNone.cond",
        canStillObtain: true,
    },
    {
        key: "ramka1000people",
        name: "frame1000.name",
        description: "frame1000.desc",
        imagePath: "/images/ramka/ramka1000people.png",
        condition: "frame1000.cond",
        canStillObtain: false,
    },
    {
        key: "ramka1-10lvl",
        name: "frameLvl1.name",
        description: "frameLvl1.desc",
        imagePath: "/images/ramka/ramka1-10lvl.png",
        condition: "frameLvl1.cond",
        minLevel: 1,
        canStillObtain: true,
    },
    {
        key: "ramka11-20lvl",
        name: "frameLvl11.name",
        description: "frameLvl11.desc",
        imagePath: "/images/ramka/ramka11-20lvl.png",
        condition: "frameLvl11.cond",
        minLevel: 11,
        canStillObtain: true,
    },
    {
        key: "ramka21-30lvl",
        name: "frameLvl21.name",
        description: "frameLvl21.desc",
        imagePath: "/images/ramka/ramka21-30lvl.png",
        condition: "frameLvl21.cond",
        minLevel: 21,
        canStillObtain: true,
    },
    {
        key: "ramka31-40lvl",
        name: "frameLvl31.name",
        description: "frameLvl31.desc",
        imagePath: "/images/ramka/ramka31-40lvl.png",
        condition: "frameLvl31.cond",
        minLevel: 31,
        canStillObtain: true,
    },
    {
        key: "ramka41-50lvl",
        name: "frameLvl41.name",
        description: "frameLvl41.desc",
        imagePath: "/images/ramka/ramka41-50lvl.png",
        condition: "frameLvl41.cond",
        minLevel: 41,
        canStillObtain: true,
    },
    {
        key: "ramka51-60lvl",
        name: "frameLvl51.name",
        description: "frameLvl51.desc",
        imagePath: "/images/ramka/ramka51-60lvl.png",
        condition: "frameLvl51.cond",
        minLevel: 51,
        canStillObtain: true,
    },
    {
        key: "ramka61-70lvl",
        name: "frameLvl61.name",
        description: "frameLvl61.desc",
        imagePath: "/images/ramka/ramka61-70lvl.png",
        condition: "frameLvl61.cond",
        minLevel: 61,
        canStillObtain: true,
    },
    {
        key: "ramka67",
        name: "frame67.name",
        description: "frame67.desc",
        imagePath: "/images/ramka/ramka67.png",
        condition: "frame67.cond",
        canStillObtain: true,
        secret: true,
    },
    {
        key: "ramka+5friend",
        name: "frame5fr.name",
        description: "frame5fr.desc",
        imagePath: "/images/ramka/ramka+5friend.png",
        condition: "frame5fr.cond",
        canStillObtain: true,
        friendsRequired: 5,
    },
    {
        key: "ramka+10friend",
        name: "frame10fr.name",
        description: "frame10fr.desc",
        imagePath: "/images/ramka/ramka+10friend.png",
        condition: "frame10fr.cond",
        canStillObtain: true,
        friendsRequired: 10,
    },
    {
        key: "ramka+25friend",
        name: "frame25fr.name",
        description: "frame25fr.desc",
        imagePath: "/images/ramka/ramka+25friend.png",
        condition: "frame25fr.cond",
        canStillObtain: true,
        friendsRequired: 25,
    },
    {
        key: "ramkaShark",
        name: "frameShark.name",
        description: "frameShark.desc",
        imagePath: "/images/ramka/ramkaShark.png",
        condition: "frameShark.cond",
        canStillObtain: true,
        secret: true,
    },
    {
        key: "ramkaUborka",
        name: "frameUborka.name",
        description: "frameUborka.desc",
        imagePath: "/images/ramka/ramkaUborka.png",
        condition: "frameUborka.cond",
        canStillObtain: true,
        secret: true,
    },
];

// name хранит i18n-ключ; перевод выполняется в ThemeSelector через t().
export const gradients = [
    { name: "grad.azure", value: "from-[#34dccb] to-[#007492]", logoKey: "AzureFlow", cursorKey: "default", cursorPath: "/images/cursor/Mouse-cursor.png" },
    { name: "grad.neon", value: "from-[#b80016] to-[#c435ac]", logoKey: "NeonPassion", cursorKey: "red", cursorPath: "/images/cursor/redMouse-cursor.png" },
    { name: "grad.space", value: "from-[#9a00b6] to-[#4362d1]", logoKey: "SpaceRift", cursorKey: "purple", cursorPath: "/images/cursor/purpleMouse-cursor.png" },
    { name: "grad.solar", value: "from-[#d76800] to-[#d7de4e]", logoKey: "SolarImpulse", cursorKey: "yellow", cursorPath: "/images/cursor/yellowMouse-cursor.png" },
    { name: "grad.tropic", value: "from-[#039e00] to-[#a4d14f]", logoKey: "TropicalPoison", cursorKey: "green", cursorPath: "/images/cursor/greenMouse-cursor.png" },
    { name: "grad.void", value: "from-[#230236] to-[#858585]", logoKey: "VoidEnergy", cursorKey: "gray", cursorPath: "/images/cursor/grayMouse-cursor.png" }
];
