export const TEMP_UNLOCK_ALL_AVATAR_FRAMES = false;

export const avatarFrames = [
    {
        key: "none",
        name: "Без рамки",
        description: "Обычный аватар без дополнительного оформления",
        imagePath: null,
        condition: "Доступно всем Premium",
        canStillObtain: true,
    },
    {
        key: "ramka1000people",
        name: "Первые 1000",
        description: "Рамка для первых 1000 пользователей Premium",
        imagePath: "/images/ramka/ramka1000people.png",
        condition: "Первые 1000 Premium",
        canStillObtain: false,
    },
    {
        key: "ramka1-10lvl",
        name: "Первые шаги",
        description: "Рамка за достижение 1 уровня",
        imagePath: "/images/ramka/ramka1-10lvl.png",
        condition: "Уровень 1+",
        minLevel: 1,
        canStillObtain: true,
    },
    {
        key: "ramka11-20lvl",
        name: "Смотрящий",
        description: "Рамка за достижение 11 уровня",
        imagePath: "/images/ramka/ramka11-20lvl.png",
        condition: "Уровень 11+",
        minLevel: 11,
        canStillObtain: true,
    },
    {
        key: "ramka21-30lvl",
        name: "Коллекционер серий",
        description: "Рамка за достижение 21 уровня",
        imagePath: "/images/ramka/ramka21-30lvl.png",
        condition: "Уровень 21+",
        minLevel: 21,
        canStillObtain: true,
    },
    {
        key: "ramka31-40lvl",
        name: "Марафонец",
        description: "Рамка за достижение 31 уровня",
        imagePath: "/images/ramka/ramka31-40lvl.png",
        condition: "Уровень 31+",
        minLevel: 31,
        canStillObtain: true,
    },
    {
        key: "ramka41-50lvl",
        name: "Ветеран онгоингов",
        description: "Рамка за достижение 41 уровня",
        imagePath: "/images/ramka/ramka41-50lvl.png",
        condition: "Уровень 41+",
        minLevel: 41,
        canStillObtain: true,
    },
    {
        key: "ramka51-60lvl",
        name: "Хранитель коллекции",
        description: "Рамка за достижение 51 уровня",
        imagePath: "/images/ramka/ramka51-60lvl.png",
        condition: "Уровень 51+",
        minLevel: 51,
        canStillObtain: true,
    },
    {
        key: "ramka61-70lvl",
        name: "Обсидиановый ранг",
        description: "Рамка за достижение 61 уровня",
        imagePath: "/images/ramka/ramka61-70lvl.png",
        condition: "Уровень 61+",
        minLevel: 61,
        canStillObtain: true,
    },
    {
        key: "ramka67",
        name: "Секретная рамка",
        description: "Особая рамка со скрытым способом получения",
        imagePath: "/images/ramka/ramka67.png",
        condition: "Условия скрыты",
        canStillObtain: true,
        secret: true,
    },
    {
        key: "ramka+5friend",
        name: "5 друзей",
        description: "Добавьте в друзья 5 человек",
        imagePath: "/images/ramka/ramka+5friend.png",
        condition: "5 приглашённых друзей",
        canStillObtain: true,
        friendsRequired: 5,
    },
    {
        key: "ramka+10friend",
        name: "10 друзей",
        description: "Добавьте в друзья 10 человек",
        imagePath: "/images/ramka/ramka+10friend.png",
        condition: "10 приглашённых друзей",
        canStillObtain: true,
        friendsRequired: 10,
    },
    {
        key: "ramka+25friend",
        name: "25 друзей",
        description: "Добавьте в друзья 25 человек",
        imagePath: "/images/ramka/ramka+25friend.png",
        condition: "25 приглашённых друзей",
        canStillObtain: true,
        friendsRequired: 25,
    },
    {
        key: "ramkaShark",
        name: "Акула",
        description: "Эксклюзивная рамка за особое достижение",
        imagePath: "/images/ramka/ramkaShark.png",
        condition: "Условия скрыты",
        canStillObtain: true,
        secret: true,
    },
    {
        key: "ramkaUborka",
        name: "Уборка",
        description: "Специальная рамка за участие в событии",
        imagePath: "/images/ramka/ramkaUborka.png",
        condition: "Условия скрыты",
        canStillObtain: true,
        secret: true,
    },
];

export const gradients = [
    { name: "Лазурный поток", value: "from-[#34dccb] to-[#007492]", logoKey: "AzureFlow", cursorKey: "default", cursorPath: "/images/cursor/Mouse-cursor.png" },
    { name: "Неоновая страсть", value: "from-[#b80016] to-[#c435ac]", logoKey: "NeonPassion", cursorKey: "red", cursorPath: "/images/cursor/redMouse-cursor.png" },
    { name: "Космический разлом", value: "from-[#9a00b6] to-[#4362d1]", logoKey: "SpaceRift", cursorKey: "purple", cursorPath: "/images/cursor/purpleMouse-cursor.png" },
    { name: "Солнечный импульс", value: "from-[#d76800] to-[#d7de4e]", logoKey: "SolarImpulse", cursorKey: "yellow", cursorPath: "/images/cursor/yellowMouse-cursor.png" },
    { name: "Тропический яд", value: "from-[#039e00] to-[#a4d14f]", logoKey: "TropicalPoison", cursorKey: "green", cursorPath: "/images/cursor/greenMouse-cursor.png" },
    { name: "Пустотная энергия", value: "from-[#230236] to-[#858585]", logoKey: "VoidEnergy", cursorKey: "gray", cursorPath: "/images/cursor/grayMouse-cursor.png" }
];